var list_data = {
    "default": {
        "hien_thi":"Bạn",
        "loi_nhan":"",
        "ten_xung":"Chúng tôi",
        "ten_goi":"Bạn"
    },
    'L1':{'hien_thi':'Gia đình bạn Lợi','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'N2':{'hien_thi':'Gia đình bạn Ngụy','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T3':{'hien_thi':'Bạn Tùng và người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T4':{'hien_thi':'Gia đình bạn Thế','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T5':{'hien_thi':'Gia đình bạn Trọng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H6':{'hien_thi':'Gia đình chú Hải','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình chú mự'},
'V7':{'hien_thi':'Gia đình Cam','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'D8':{'hien_thi':'Gia đình bạn Dương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'C9':{'hien_thi':'Gia đình bạn Chiến','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'V10':{'hien_thi':'Gia đình bạn Vũ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Đ11':{'hien_thi':'Bạn Đức và người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H12':{'hien_thi':'Gia đình chú mự Hùng Hằng','loi_nhan':'','ten_xung':'vợ chồng bác','ten_goi':'gia đình chú mự'},
'C13':{'hien_thi':'Gia đình chú Cương','loi_nhan':'','ten_xung':'vợ chồng bác','ten_goi':'gia đình chú mự'},
'Đ14':{'hien_thi':'Anh Độ và người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'Đ15':{'hien_thi':'Gia đình anh Đức','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'C16':{'hien_thi':'Gia đình chú Phúc','loi_nhan':'','ten_xung':'vợ chồng cháu','ten_goi':'gia đình chú mự'},
'C17':{'hien_thi':'Gia đình chú Thọ','loi_nhan':'','ten_xung':'vợ chồng cháu','ten_goi':'gia đình chú mự'},
'O18':{'hien_thi':'Gia đình O Hằng','loi_nhan':'','ten_xung':'vợ chồng cậu','ten_goi':'gia đình O'},
'C19':{'hien_thi':'Gia đình chú Cảnh','loi_nhan':'','ten_xung':'vợ chồng bác','ten_goi':'gia đình chú mự'},
'T20':{'hien_thi':'Gia đình chú Toàn','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chú mự'},
'T21':{'hien_thi':'Gia đình O Tâm Toàn','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình O'},
'A22':{'hien_thi':'Gia đình Kem','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'E23':{'hien_thi':'Em Hiệp & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Q24':{'hien_thi':'Em Quang & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Đ25':{'hien_thi':'Em Đức & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Y26':{'hien_thi':'Em Yến & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'T27':{'hien_thi':'Bạn Tần & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H28':{'hien_thi':'Gia đình bạn Hải','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H29':{'hien_thi':'Gia đình anh Hưng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Đ30':{'hien_thi':'Gia đình anh Đức','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'B31':{'hien_thi':'Gia đình anh Bảo','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'H32':{'hien_thi':'Gia đình anh Hưng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'H33':{'hien_thi':'Gia đình bạn Hùng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H34':{'hien_thi':'Gia đình bạn Hòa','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T35':{'hien_thi':'Gia đình bạn Tình','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T36':{'hien_thi':'Gia đình bạn Tứ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T37':{'hien_thi':'Gia đình anh Tuấn','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'B38':{'hien_thi':'Bạn Bình & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'B39':{'hien_thi':'Gia đình anh Báu','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'S40':{'hien_thi':'Gia đình bạn Sơn','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H41':{'hien_thi':'Gia đình Em Hạnh','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'T42':{'hien_thi':'Em Tuấn và người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Đ43':{'hien_thi':'Gia đình anh Đồng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'K44':{'hien_thi':'Gia đình anh Kỳ','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'D45':{'hien_thi':'Gia đình anh Dũng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'T46':{'hien_thi':'Gia đình anh Thắng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'T47':{'hien_thi':'Em Thanh và người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'S48':{'hien_thi':'Gia đình bạn Sơn','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T49':{'hien_thi':'Em Tư và người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'H50':{'hien_thi':'Gia đình O Huế','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình O'},
'T51':{'hien_thi':'Gia đình Em Thắng','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'B52':{'hien_thi':'Anh Bình & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'V53':{'hien_thi':'Gia đình bạn Việt','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Q54':{'hien_thi':'Bạn Quỳnh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'B55':{'hien_thi':'Anh Bắc & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'T56':{'hien_thi':'Gia đình chú Trung','loi_nhan':'','ten_xung':'vợ chồng cháu','ten_goi':'gia đình chú mự'},
'T57':{'hien_thi':'Gia đình Em Thọ','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'M58':{'hien_thi':'Gia đình O Mai','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình O'},
'C59':{'hien_thi':'Em Chiến & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'C60':{'hien_thi':'Em Chiến & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'C61':{'hien_thi':'Em Cường & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'D62':{'hien_thi':'Gia đình Em Dũng','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},

'Q64':{'hien_thi':'Bạn Quang & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'K65':{'hien_thi':'Idol & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'idol'},
'K66':{'hien_thi':'Em Khánh & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'H67':{'hien_thi':'Em Hà & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'H68':{'hien_thi':'Gia đình Em Hùng','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'V69':{'hien_thi':'Gia đình Em Viết','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'P70':{'hien_thi':'Gia đình bạn Phong','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'P71':{'hien_thi':'Gia đình anh Phú','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'T72':{'hien_thi':'Gia đình anh Thái','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'H73':{'hien_thi':'Gia đình bạn Hoàng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'V74':{'hien_thi':'Em Vũ Long & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Đ75':{'hien_thi':'Gia đình bạn Đức','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T76':{'hien_thi':'Gia đình bạn Thành','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T77':{'hien_thi':'Gia đình bạn Trung','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'L78':{'hien_thi':'Gia đình bạn Linh','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'L79':{'hien_thi':'Gia đình bạn Long','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'C80':{'hien_thi':'Gia đình Cô Dung','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình cô'},
'L81':{'hien_thi':'Gia đình bạn Làn','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Đ82':{'hien_thi':'Gia đình bạn Đài','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'C83':{'hien_thi':'Gia đình bạn Chiến','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H84':{'hien_thi':'Gia đình bạn Hào','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'K85':{'hien_thi':'Gia đình bạn Kỷ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'L86':{'hien_thi':'Gia đình bạn Lý','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'P87':{'hien_thi':'Gia đình bạn Phi','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'K88':{'hien_thi':'Gia đình bạn Kỳ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H89':{'hien_thi':'Gia đình bạn Hà','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'S90':{'hien_thi':'Gia đình bạn Hà','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H91':{'hien_thi':'Gia đình bạn Hằng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H92':{'hien_thi':'Gia đình bạn Hằng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H93':{'hien_thi':'Gia đình bạn Hoàn','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H94':{'hien_thi':'Gia đình bạn Hoàng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H95':{'hien_thi':'Gia đình bạn Hạnh','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T96':{'hien_thi':'Gia đình bạn Trang','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'N97':{'hien_thi':'Gia đình bạn Nam','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'N98':{'hien_thi':'Gia đình bạn Ngọc','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'N99':{'hien_thi':'Gia đình bạn Ngọc','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'L100':{'hien_thi':'Gia đình bạn Lý','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T101':{'hien_thi':'Gia đình bạn Trung','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'T102':{'hien_thi':'Gia đình bạn Thứ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H103':{'hien_thi':'Gia đình bạn Hải','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H104':{'hien_thi':'Gia đình anh Hải','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'H105':{'hien_thi':'Em Hải & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'V106':{'hien_thi':'Bạn Vũ & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H107':{'hien_thi':'Gia đình Em Huỳnh','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'T108':{'hien_thi':'Em Toản & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'H109':{'hien_thi':'Em Hằng & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'H110':{'hien_thi':'Gia đình chị Hiền','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Y111':{'hien_thi':'Gia đình chị Yến','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'T112':{'hien_thi':'Anh Tuấn & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'L113':{'hien_thi':'Gia đình Em Luận','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'S114':{'hien_thi':'Em Sơn & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'L115':{'hien_thi':'Gia đình Em Liên','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'C116':{'hien_thi':'Gia đình chị Thanh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'A117':{'hien_thi':'Gia đình anh Anh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'C118':{'hien_thi':'Chị Thủy & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'C119':{'hien_thi':'Gia đình chị Vinh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'A120':{'hien_thi':'Gia đình anh Công','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'A121':{'hien_thi':'Gia đình anh Bằng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'C122':{'hien_thi':'Gia đình chị Dương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'A123':{'hien_thi':'Gia đình anh Bắc','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'C124':{'hien_thi':'Gia đình chị Phương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'A125':{'hien_thi':'Gia đình anh Việt','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'C126':{'hien_thi':'Gia đình chị Hà','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'C127':{'hien_thi':'Gia đình chị Trang','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'C128':{'hien_thi':'Cháu Tiến & người thương','loi_nhan':'','ten_xung':'vợ chồng cậu','ten_goi':'cháu'},
'C129':{'hien_thi':'Cháu Phương & người thương','loi_nhan':'','ten_xung':'vợ chồng cậu','ten_goi':'cháu'},
'C130':{'hien_thi':'Cháu Nam & người thương','loi_nhan':'','ten_xung':'vợ chồng cậu','ten_goi':'cháu'},
'Đ131':{'hien_thi':'Gia đình bạn Đạt','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'D132':{'hien_thi':'Gia đình anh Dân','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'D133':{'hien_thi':'Gia đình Em Dũng','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'N134':{'hien_thi':'Gia đình Em Ngũ','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'D135':{'hien_thi':'Gia đình Nana','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'H136':{'hien_thi':'Gia đình chị Hằng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'T137':{'hien_thi':'Em Trọng & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'B138':{'hien_thi':'Em Bình & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'S139':{'hien_thi':'Gia đình anh Sơn','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'S140':{'hien_thi':'Gia đình bạn Sơn','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Q141':{'hien_thi':'Gia đình anh Quyển','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'H142':{'hien_thi':'Em Huy & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'L143':{'hien_thi':'Em Long & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'T144':{'hien_thi':'Gia đình Em Thúy','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'A145':{'hien_thi':'Gia đình anh Tín','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'N146':{'hien_thi':'Gia đình anh Ngọc Ảnh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'M147':{'hien_thi':'Gia đình Em Minh','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'L148':{'hien_thi':'Anh Long & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'N149':{'hien_thi':'Em Dương & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'C150':{'hien_thi':'Gia đình bạn Chinh','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'H151':{'hien_thi':'Gia đình bạn Hải','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Đ152':{'hien_thi':'Gia đình Lão Đạo','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình Lão đại'},
'V153':{'hien_thi':'Gia đình bạn Vỹ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'C154':{'hien_thi':'Chị Hà & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'C155':{'hien_thi':'Gia đình chú Quý','loi_nhan':'','ten_xung':'vợ chồng cháu','ten_goi':'gia đình cô chú'},
'A156':{'hien_thi':'Gia đình anh Lợi','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'C157':{'hien_thi':'Gia đình chị Bông','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'S158':{'hien_thi':'Em Sang & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'P159':{'hien_thi':'Gia đình bạn Phố','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'B160':{'hien_thi':'Bạn Bắc & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T161':{'hien_thi':'Tập thể lớp A7','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'tập thể lớp'},
'T162':{'hien_thi':'Tập thể lớp 9C','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'tập thể lớp'},
'T163':{'hien_thi':'Tập thể công ty KISVN','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'tập thể công ty'},
'T164':{'hien_thi':'Tập thể lớp A1','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'tập thể lớp'},
'C165':{'hien_thi':'Tập thể công ty BH Media','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'tập thể công ty'},
'C166':{'hien_thi':'Gia đình chị Mai','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'Y167':{'hien_thi':'Gia đình bạn Yến','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'bạn'},
'C168':{'hien_thi':'Gia đình chị Oanh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'C169':{'hien_thi':'Chị Mai & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'C170':{'hien_thi':'Chị Ngọc & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'C171':{'hien_thi':'Gia đình chị Yến','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'C172':{'hien_thi':'Gia đình chị Ngân','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'C173':{'hien_thi':'Gia đình chị Gấm','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'C174':{'hien_thi':'Gia đình chị Hương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'C175':{'hien_thi':'Gia đình chị Oanh và anh Bình','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh chị'},
'A176':{'hien_thi':'Anh Ngọc & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'C177':{'hien_thi':'Chị Trang & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'A178':{'hien_thi':'Gia đình anh Hải','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'A179':{'hien_thi':'Vợ chồng anh Phú','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'C180':{'hien_thi':'Chị Linh & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'T181':{'hien_thi':'Em Thùy & người thương','loi_nhan':'','ten_xung':'vợ chồng chị','ten_goi':'em'},
'A182':{'hien_thi':'Gia đình anh Huy','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'A183':{'hien_thi':'Gia đình anh Quý','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'A184':{'hien_thi':'Anh Luật & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'M185':{'hien_thi':'Bạn Minh Trang & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H186':{'hien_thi':'Gia đình em Hằng Đức','loi_nhan':'','ten_xung':'vợ chồng chị','ten_goi':'em'},
'L187':{'hien_thi':'Gia đình em Linh Tuấn','loi_nhan':'','ten_xung':'vợ chồng chị','ten_goi':'em'},
'H188':{'hien_thi':'Em Hạnh & Người thương','loi_nhan':'','ten_xung':'vợ chồng chị','ten_goi':'em'},
'B189':{'hien_thi':'Em Giang','loi_nhan':'','ten_xung':'vợ chồng chị','ten_goi':'em'},
'N190':{'hien_thi':'Gia đình em Như','loi_nhan':'','ten_xung':'vợ chồng chị','ten_goi':'em'},
'P191':{'hien_thi':'Gia đình em Phương','loi_nhan':'','ten_xung':'vợ chồng chị','ten_goi':'em'},
'C192':{'hien_thi':'Chú Hùng & người thương','loi_nhan':'','ten_xung':'vợ chồng con','ten_goi':'chú'},
'O193':{'hien_thi':'Gia đình O Nga','loi_nhan':'','ten_xung':'vợ chồng con','ten_goi':'O'},
'O194':{'hien_thi':'Gia đình O Bích','loi_nhan':'','ten_xung':'vợ chồng con','ten_goi':'O'},
'O195':{'hien_thi':'Gia đình O Bính','loi_nhan':'','ten_xung':'vợ chồng con','ten_goi':'O'},
'O196':{'hien_thi':'Gia đình O Thảo','loi_nhan':'','ten_xung':'vợ chồng con','ten_goi':'O'},
'C197':{'hien_thi':'Gia đình cậu Hoàng','loi_nhan':'','ten_xung':'vợ chồng con','ten_goi':'Cậu'},
'C198':{'hien_thi':'Gia đình cậu Tùng','loi_nhan':'','ten_xung':'vợ chồng con','ten_goi':'Cậu'},
'ô199':{'hien_thi':'Gia đình ông Công','loi_nhan':'','ten_xung':'vợ chồng con','ten_goi':'Ông'},
'a200':{'hien_thi':'Gia đình anh Văn','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'A201':{'hien_thi':'Gia đình anh Hoa','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'a202':{'hien_thi':'Gia đình anh Hạnh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'a203':{'hien_thi':'Gia đình anh Hải','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'c204':{'hien_thi':'Gia đình chị Huệ','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'a205':{'hien_thi':'Gia đình anh Huy','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'a206':{'hien_thi':'Gia đình anh Hiệu','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'c207':{'hien_thi':'Chị Dung','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'c208':{'hien_thi':'Gia đình chị Hương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'a209':{'hien_thi':'Anh Hùng & Người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'a210':{'hien_thi':'Anh Quang & Người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'c211':{'hien_thi':'Chị bé & Người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'C212':{'hien_thi':'Gia đình chị Thắm','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'A213':{'hien_thi':'Gia đình anh Đồng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'C214':{'hien_thi':'Chị Loan & Người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'L215':{'hien_thi':'Bác Linh & Người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'bác'},
'A216':{'hien_thi':'Gia đình anh Nam','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'Y217':{'hien_thi':'Bác Ý','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'bác'},
'C218':{'hien_thi':'Gia đình chị Thúy','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'T219':{'hien_thi':'Vợ chồng bạn Oanh','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'vợ chồng bạn'},
'L220':{'hien_thi':'Bạn Luật & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'V221':{'hien_thi':'Bạn Văn Đức & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T222':{'hien_thi':'Bạn Thiện Đức & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'V223':{'hien_thi':'Bạn Viết & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T224':{'hien_thi':'Bạn Trai & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H225':{'hien_thi':'Bạn Hậu & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'B226':{'hien_thi':'Bạn Bảo & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'N227':{'hien_thi':'Bạn Nhật & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H228':{'hien_thi':'Bạn Hồng Minh & bạn Đức','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Q229':{'hien_thi':'Bạn Quy & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T230':{'hien_thi':'Bạn Tuấn Vũ & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H231':{'hien_thi':'Bạn Hà & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'D232':{'hien_thi':'Bạn Dũng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'G233':{'hien_thi':'Gia đình bạn Giang','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'vợ chồng bạn'},
'H234':{'hien_thi':'Bạn Hải & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H235':{'hien_thi':'Bạn Huyền & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Q236':{'hien_thi':'Bạn Quý & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T237':{'hien_thi':'Bạn Thủy & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T238':{'hien_thi':'Bạn Tuyết & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Đ239':{'hien_thi':'Bạn Đức & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Đ240':{'hien_thi':'Bạn Đức & bạn Minh','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'B241':{'hien_thi':'Bạn Ba  & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'm242':{'hien_thi':'Bạn Mạnh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Đ243':{'hien_thi':'Bạn Đại & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H244':{'hien_thi':'Bạn Hào & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'S245':{'hien_thi':'Bạn Sơn & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'C246':{'hien_thi':'Bạn Chiến & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H247':{'hien_thi':'Bạn Hằng Phùng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'K248':{'hien_thi':'Bạn Kiên & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H249':{'hien_thi':'Bạn Huế & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'M250':{'hien_thi':'Bạn Mỹ & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'L251':{'hien_thi':'Bạn Linh Tú & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H252':{'hien_thi':'Bạn Hà & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Đ253':{'hien_thi':'Bạn Đăng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T254':{'hien_thi':'Bạn Thảo thiết & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'N255':{'hien_thi':'Bạn Na Vĩnh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'V256':{'hien_thi':'Bạn Vân & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H257':{'hien_thi':'Bạn Huệ & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'C258':{'hien_thi':'Bạn Công & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T259':{'hien_thi':'Bạn Trang & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'V260':{'hien_thi':'Bạn Việt Hà & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'K261':{'hien_thi':'Bạn Khánh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'N262':{'hien_thi':'Bạn Ngọc & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T263':{'hien_thi':'Gia đình thầy Đồng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình Thầy'},
'T264':{'hien_thi':'Gia đình thầy Quỳnh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình Thầy'},
'H265':{'hien_thi':'Bạn Hiếu & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'V266':{'hien_thi':'Bạn Vân & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H267':{'hien_thi':'Bạn Huệ Thư & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H268':{'hien_thi':'Bạn Hằng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T269':{'hien_thi':'Bạn Thu & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T270':{'hien_thi':'Gia đình bạn Thảo','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'vợ chồng bạn'},
'L271':{'hien_thi':'Bạn Linh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H272':{'hien_thi':'Bạn Hoàng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'T273':{'hien_thi':'Bạn Thùy & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'G274':{'hien_thi':'Bạn Giang & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'A275':{'hien_thi':'Bạn Anh Sơn & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'C276':{'hien_thi':'Chị Như & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H277':{'hien_thi':'Bạn Hằng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'chị'},
'T278':{'hien_thi':'Em Toàn Quế & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'H279':{'hien_thi':'Em Huyền Cù & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'V280':{'hien_thi':'Gia đình bạn Hằng Khải','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'vợ chồng bạn'},
'A281':{'hien_thi':'Gia đình anh Nhật','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'A282':{'hien_thi':'Anh Hưng & Người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'H283':{'hien_thi':'Em Hiền & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'em'},
'v284':{'hien_thi':'Bạn Võ & Người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'A285':{'hien_thi':'Anh Nhuệ & Người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'A286':{'hien_thi':'Gia đình anh Hậu','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'Q287':{'hien_thi':'Bạn Quân & Người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'B288':{'hien_thi':'Gia đình anh Công','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
};

$( document ).ready(function() {
    loadList();
});

var loadList = function(){
    var url = new URL(window.location);
    var c = url.searchParams.get("n");
    var my_default = list_data.default;
    var obj = list_data.default;
    if(c && list_data[c]){
        obj = list_data[c];
    }
    debugger
    if(obj.loi_nhan){
        $("#loi_nhan").text(obj.loi_nhan || my_default.loi_nhan);
    }
    
    $("#nguoi_dc_moi").text(obj.hien_thi || my_default.hien_thi);
    $("#ip_name").val(obj.hien_thi || my_default.hien_thi);
    $("#ip_phone").val(obj.sdt || my_default.sdt);
    $(".ten_xung").text(obj.ten_xung || my_default.ten_xung);
    $(".ten_goi").text(jsUcfirst(obj.ten_goi) || jsUcfirst(my_default.ten_goi));
    $("#show_bank").hide();
    if(obj.show_bank){
        $("#show_bank").show();
    }
    
}
function jsUcfirst(string) 
{
    if(string){
        return string.charAt(0).toUpperCase() + string.slice(1);
    }
    return string;
}
