var list_data = {
    "default": {
        "hien_thi":"Bạn",
        "loi_nhan":"",
        "ten_xung":"Chúng tôi",
        "ten_goi":"Bạn"
    },
    'Loi':{'hien_thi':'Gia đình bạn Lợi','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Nguy':{'hien_thi':'Gia đình bạn Ngụy','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Tung_Binh':{'hien_thi':'Bạn Tùng và người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'The_Ty':{'hien_thi':'Gia đình bạn Thế','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Trong_Cong':{'hien_thi':'Gia đình bạn Trọng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hai_Thuong':{'hien_thi':'Gia đình chú Hải','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình chú mự'},
'Viet_Nhuong':{'hien_thi':'Gia đình Cam','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Duong_Long':{'hien_thi':'Gia đình bạn Dương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Chien_Kiem':{'hien_thi':'Gia đình bạn Chiến','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Vu_Ly':{'hien_thi':'Gia đình bạn Vũ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Duc_Ngoan':{'hien_thi':'Bạn Đức và người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hung_Nghien':{'hien_thi':'Gia đình chú mự Hùng Hằng','loi_nhan':'','ten_xung':'vợ chồng bác','ten_goi':'gia đình chú mự'},
'Cuong_Nghien':{'hien_thi':'Gia đình chú Cương','loi_nhan':'','ten_xung':'vợ chồng bác','ten_goi':'gia đình chú mự'},
'Do_Tung':{'hien_thi':'Anh Độ và người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'Duc_Tung':{'hien_thi':'Gia đình anh Đức','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Chu_Phuc':{'hien_thi':'Gia đình chú Phúc','loi_nhan':'','ten_xung':'vợ chồng cháu','ten_goi':'gia đình chú mự'},
'Chu_Tho':{'hien_thi':'Gia đình chú Thọ','loi_nhan':'','ten_xung':'vợ chồng cháu','ten_goi':'gia đình chú mự'},
'O_Hang':{'hien_thi':'Gia đình O Hằng','loi_nhan':'','ten_xung':'vợ chồng cậu','ten_goi':'gia đình O'},
'Canh_Cu':{'hien_thi':'Gia đình chú Cảnh','loi_nhan':'','ten_xung':'vợ chồng bác','ten_goi':'gia đình chú mự'},
'Toan_Cu':{'hien_thi':'Gia đình chú Toàn','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chú mự'},
'Tam_Tung':{'hien_thi':'Gia đình O Tâm Toàn','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình O'},
'Anh_Thieu':{'hien_thi':'Gia đình Kem','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Em_Hiep_Ban_Anh':{'hien_thi':'Em Hiệp & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Quang_Dien':{'hien_thi':'Em Quang & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Duc_Thin':{'hien_thi':'Em Đức & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Yen_Dien':{'hien_thi':'Em Yến & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Tan_Chau':{'hien_thi':'Bạn Tần & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hai_Tuan':{'hien_thi':'Gia đình bạn Hải','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hung_Quang':{'hien_thi':'Gia đình anh Hưng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Duc_Quang':{'hien_thi':'Gia đình anh Đức','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Bao_Quang':{'hien_thi':'Gia đình anh Bảo','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Hung_Chuan':{'hien_thi':'Gia đình anh Hưng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Hung_Lam':{'hien_thi':'Gia đình bạn Hùng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hoa_Lam':{'hien_thi':'Gia đình bạn Hòa','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Tinh_Chat':{'hien_thi':'Gia đình bạn Tình','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Tu_Chat':{'hien_thi':'Gia đình bạn Tứ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Tuan_Chat':{'hien_thi':'Gia đình anh Tuấn','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Binh_Bau':{'hien_thi':'Bạn Bình & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Bau_Quyen':{'hien_thi':'Gia đình anh Báu','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Son_Quyen':{'hien_thi':'Gia đình bạn Sơn','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hanh_Thanh':{'hien_thi':'Gia đình Em Hạnh','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Tuan_Thanh':{'hien_thi':'Em Tuấn và người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Dong_Tung':{'hien_thi':'Gia đình anh Đồng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Ky_Hanh':{'hien_thi':'Gia đình anh Kỳ','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Dung_Duc':{'hien_thi':'Gia đình anh Dũng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Thang_Duc':{'hien_thi':'Gia đình anh Thắng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Thanh_Duc':{'hien_thi':'Em Thanh và người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Son_Thuan':{'hien_thi':'Gia đình bạn Sơn','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Tu_Nhi':{'hien_thi':'Em Tư và người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Hue_Chau':{'hien_thi':'Gia đình O Huế','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình O'},
'Thang_Lan':{'hien_thi':'Gia đình Em Thắng','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Binh_Hu':{'hien_thi':'Anh Bình & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'Viet_Toan':{'hien_thi':'Gia đình bạn Việt','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Quynh_Sang':{'hien_thi':'Bạn Quỳnh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Bac_Ngon':{'hien_thi':'Anh Bắc & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'Trung_Lien':{'hien_thi':'Gia đình chú Trung','loi_nhan':'','ten_xung':'vợ chồng cháu','ten_goi':'gia đình chú mự'},
'Tho_Nga':{'hien_thi':'Gia đình Em Thọ','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Mai_Linh':{'hien_thi':'Gia đình O Mai','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình O'},
'Chien_Thich':{'hien_thi':'Em Chiến & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Chien_Mao':{'hien_thi':'Em Chiến & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Cuong_Ni':{'hien_thi':'Em Cường & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Dung_Binh':{'hien_thi':'Gia đình Em Dũng','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Quang_Beo':{'hien_thi':'Bạn Quang & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Khanh_Coi_CT':{'hien_thi':'Idol & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'idol'},
'Khanh_Luc':{'hien_thi':'Em Khánh & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Ha_Cong':{'hien_thi':'Em Hà & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Hung_Am':{'hien_thi':'Gia đình Em Hùng','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Viet_Cam_Ha':{'hien_thi':'Gia đình Em Viết','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Phong_Cho':{'hien_thi':'Gia đình bạn Phong','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Phu_Ce':{'hien_thi':'Gia đình anh Phú','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Thai_Cho':{'hien_thi':'Gia đình anh Thái','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Hoang_Cam_Lac':{'hien_thi':'Gia đình bạn Hoàng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Vu_Long':{'hien_thi':'Em Vũ Long & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Duc_Nhuong':{'hien_thi':'Gia đình bạn Đức','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Thanh_Son':{'hien_thi':'Gia đình bạn Thành','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Trung_Van':{'hien_thi':'Gia đình bạn Trung','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Linh_Dai':{'hien_thi':'Gia đình bạn Linh','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Long_Xanh':{'hien_thi':'Gia đình bạn Long','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Co_Dung':{'hien_thi':'Gia đình Cô Dung','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình cô'},
'Lan_Lieu':{'hien_thi':'Gia đình bạn Làn','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Dai_Hai':{'hien_thi':'Gia đình bạn Đài','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Chien_Hai':{'hien_thi':'Gia đình bạn Chiến','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hao_Xuan':{'hien_thi':'Gia đình bạn Hào','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Ky_Huyen':{'hien_thi':'Gia đình bạn Kỷ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Ly_Tien':{'hien_thi':'Gia đình bạn Lý','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Phi_Linh':{'hien_thi':'Gia đình bạn Phi','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Ky_Son':{'hien_thi':'Gia đình bạn Kỳ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Ha_Cong':{'hien_thi':'Gia đình bạn Hà','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Sy_Ha':{'hien_thi':'Gia đình bạn Hà','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hang_Chien':{'hien_thi':'Gia đình bạn Hằng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hang_Dan':{'hien_thi':'Gia đình bạn Hằng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hoan_Quy':{'hien_thi':'Gia đình bạn Hoàn','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hoang_Lem':{'hien_thi':'Gia đình bạn Hoàng','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hanh_Coi':{'hien_thi':'Gia đình bạn Hạnh','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Trang_Beo':{'hien_thi':'Gia đình bạn Trang','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Nam_Tuong':{'hien_thi':'Gia đình bạn Nam','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Ngoc_Luong':{'hien_thi':'Gia đình bạn Ngọc','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Ngoc_B':{'hien_thi':'Gia đình bạn Ngọc','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Ly_Sinh':{'hien_thi':'Gia đình bạn Lý','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Trung_Coi':{'hien_thi':'Gia đình bạn Trung','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Thu_Tu':{'hien_thi':'Gia đình bạn Thứ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hai_To':{'hien_thi':'Gia đình bạn Hải','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hai_Bo':{'hien_thi':'Gia đình anh Hải','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Hai_Truon':{'hien_thi':'Em Hải & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Vu_Thi_Tran':{'hien_thi':'Bạn Vũ & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Huynh_Hieu':{'hien_thi':'Gia đình Em Huỳnh','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Toan_Coc':{'hien_thi':'Em Toản & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Hang_Tran_ctrung':{'hien_thi':'Em Hằng & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Hien_Tue':{'hien_thi':'Gia đình chị Hiền','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Yen_Tue':{'hien_thi':'Gia đình chị Yến','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Tuan_Tue':{'hien_thi':'Anh Tuấn & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'Luan_Ly':{'hien_thi':'Gia đình Em Luận','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Son_Ly':{'hien_thi':'Em Sơn & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Lien_Ly':{'hien_thi':'Gia đình Em Liên','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Chi_Thanh':{'hien_thi':'Gia đình chị Thanh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Anh_Anh':{'hien_thi':'Gia đình anh Anh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Chi_Thuy':{'hien_thi':'Chị Thủy & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'Chi_Vinh':{'hien_thi':'Gia đình chị Vinh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Anh_Cong':{'hien_thi':'Gia đình anh Công','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Anh_Bang':{'hien_thi':'Gia đình anh Bằng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Chi_Duong':{'hien_thi':'Gia đình chị Dương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Anh_Bac':{'hien_thi':'Gia đình anh Bắc','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Chi_Phuong':{'hien_thi':'Gia đình chị Phương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Anh_Viet':{'hien_thi':'Gia đình anh Việt','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Chi_Ha':{'hien_thi':'Gia đình chị Hà','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Chi_Trang':{'hien_thi':'Gia đình chị Trang','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Chau_Tien':{'hien_thi':'Cháu Tiến & người thương','loi_nhan':'','ten_xung':'vợ chồng cậu','ten_goi':'cháu'},
'Chau_Phuong':{'hien_thi':'Cháu Phương & người thương','loi_nhan':'','ten_xung':'vợ chồng cậu','ten_goi':'cháu'},
'Chau_Chay':{'hien_thi':'Cháu Nam & người thương','loi_nhan':'','ten_xung':'vợ chồng cậu','ten_goi':'cháu'},
'Dat_lzt':{'hien_thi':'Gia đình bạn Đạt','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Dan_lzt':{'hien_thi':'Gia đình anh Dân','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Dung_lzt':{'hien_thi':'Gia đình Em Dũng','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Ngu_lzt':{'hien_thi':'Gia đình Em Ngũ','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Duy_lzt':{'hien_thi':'Gia đình Nana','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Hang_lzt':{'hien_thi':'Gia đình chị Hằng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Trong_lzt':{'hien_thi':'Em Trọng & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Binh_lzt':{'hien_thi':'Em Bình & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Son_Tung_lzt':{'hien_thi':'Gia đình anh Sơn','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Son_lien_lzt':{'hien_thi':'Gia đình bạn Sơn','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Quyen_lzt':{'hien_thi':'Gia đình anh Quyển','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Huy_nho_lzt':{'hien_thi':'Em Huy & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Long_nho_lzt':{'hien_thi':'Em Long & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Thuy_lzt':{'hien_thi':'Gia đình Em Thúy','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Anh_Tin_lzt':{'hien_thi':'Gia đình anh Tín','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Ngoc_Anh_lzt':{'hien_thi':'Gia đình anh Ngọc Ảnh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Minh_lzt':{'hien_thi':'Gia đình Em Minh','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'gia đình em'},
'Long_lzt':{'hien_thi':'Anh Long & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'anh'},
'Nam_Duong':{'hien_thi':'Em Dương & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Chinh_Ga':{'hien_thi':'Gia đình bạn Chinh','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Hai':{'hien_thi':'Gia đình bạn Hải','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Dai':{'hien_thi':'Gia đình Lão Đạo','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình Lão đại'},
'Vy_Luc':{'hien_thi':'Gia đình bạn Vỹ','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Chi_Ha':{'hien_thi':'Chị Hà & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'Chu_Quy':{'hien_thi':'Gia đình chú Quý','loi_nhan':'','ten_xung':'vợ chồng cháu','ten_goi':'gia đình cô chú'},
'Anh_Loi':{'hien_thi':'Gia đình anh Lợi','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình anh'},
'Chi_Bong':{'hien_thi':'Gia đình chị Bông','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình chị'},
'Sang_Cot':{'hien_thi':'Em Sang & người thương','loi_nhan':'','ten_xung':'vợ chồng anh','ten_goi':'em'},
'Pho_Nha':{'hien_thi':'Gia đình bạn Phố','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'gia đình bạn'},
'Bac_Bang':{'hien_thi':'Bạn Bắc & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'A7':{'hien_thi':'Tập thể lớp A7','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'tập thể lớp'},
'9C':{'hien_thi':'Tập thể lớp 9C','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'tập thể lớp'},
'KISVN':{'hien_thi':'Tập thể công ty KISVN','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'tập thể công ty'},
'A1':{'hien_thi':'Tập thể lớp A1','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'tập thể lớp'},
'BHMedia':{'hien_thi':'Tập thể công ty BH Media','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'tập thể công ty'},
'Chi_mai_le':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Yen_nguyen':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_oanh_kieu':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_mai_nguyen':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_ngoc':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_yen_bui':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_ngan':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_gam':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_huong':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_lam_oanh_+_sep':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'A_ngoc':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_trang':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_hai_it':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_phu':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_dieu_linh':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Thuy_do':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_huy':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_quy':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_luat':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Minh_trang':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Hang_tinh':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Linh_tinh':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Hanh_tinh':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Be_tinh':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Nhu_tich':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Phuong_tich':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chu_hung':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'O_nga':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'O_bich':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'O_binh':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'O_thao':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Cau_Hoang':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Cau_Tung':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'ong_cong':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'anh_Van':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_Hoa':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'anh_Hanh':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'anh_Hai':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'chi_Hue':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'anh_Huy':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'anh_Hieu':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'chi_dung':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'chi_huong':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'anh_Hung':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'anh_quang':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'chi_be':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_Tham':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_Dong':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_Loan':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Linh_Man':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_Nam':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Y_Viet':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Chi_Thuy_Chien':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Truong_Oanh':{'hien_thi':'Vợ chồng bạn Oanh','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'vợ chồng bạn'},
'Luat':{'hien_thi':'Bạn Luật & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Van_Duc':{'hien_thi':'Bạn Văn Đức & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Thien_Duc':{'hien_thi':'Bạn Thiện Đức & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Viet':{'hien_thi':'Bạn Viết & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Trai':{'hien_thi':'Bạn Trai & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hau':{'hien_thi':'Bạn Hậu & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Bao':{'hien_thi':'Bạn Bảo & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Nhat':{'hien_thi':'Bạn Nhật & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hong_Minh':{'hien_thi':'Bạn Hồng Minh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Quy':{'hien_thi':'Bạn Quy & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Tuan_Vu':{'hien_thi':'Bạn Tuấn Vũ & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Ha_Hue':{'hien_thi':'Bạn Hà & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Dung':{'hien_thi':'Bạn Dũng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Giang_Thai':{'hien_thi':'Gia đình bạn Giang','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'vợ chồng bạn'},
'Hai':{'hien_thi':'Bạn Hải & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Huyen':{'hien_thi':'Bạn Huyền & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Quy':{'hien_thi':'Bạn Quý & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Thuy':{'hien_thi':'Bạn Thủy & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Tuyet':{'hien_thi':'Bạn Tuyết & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Duc_Ve':{'hien_thi':'Bạn Đức & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Duc_Son':{'hien_thi':'Bạn Đức & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Ba_':{'hien_thi':'Bạn Ba  & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'manh':{'hien_thi':'Bạn Mạnh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Dai':{'hien_thi':'Bạn Đại & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hao':{'hien_thi':'Bạn Hào & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Son':{'hien_thi':'Bạn Sơn & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Chien_':{'hien_thi':'Bạn Chiến & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hang_Phung':{'hien_thi':'Bạn Hằng Phùng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Kien':{'hien_thi':'Bạn Kiên & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hue':{'hien_thi':'Bạn Huế & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'My':{'hien_thi':'Bạn Mỹ & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Linh_Tu':{'hien_thi':'Bạn Linh Tú & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Ha_Kien':{'hien_thi':'Bạn Hà & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Dang':{'hien_thi':'Bạn Đăng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Thao_thiet':{'hien_thi':'Bạn Thảo thiết & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Na_Vinh':{'hien_thi':'Bạn Na Vĩnh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Van_Cuong':{'hien_thi':'Bạn Vân & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hue_Huy':{'hien_thi':'Bạn Huệ & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Cong_Quyet':{'hien_thi':'Bạn Công & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Trang_Thoi':{'hien_thi':'Bạn Trang & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Viet_Ha':{'hien_thi':'Bạn Việt Hà & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Khanh_Linh':{'hien_thi':'Bạn Khánh Linh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Ngoc_Luan':{'hien_thi':'Bạn Ngọc Luận & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Thay_Dong':{'hien_thi':'Gia đình thầy Đồng','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình Thầy'},
'Thay_Quynh':{'hien_thi':'Gia đình thầy Quỳnh','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'gia đình Thầy'},
'Hieu':{'hien_thi':'Bạn Hiếu & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Van__':{'hien_thi':'Bạn Vân & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hue_Thu':{'hien_thi':'Bạn Huệ Thư & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hang_ty':{'hien_thi':'Bạn Hằng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Thu_':{'hien_thi':'Bạn Thu & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Thao_Beu':{'hien_thi':'Gia đình bạn Thảo','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'vợ chồng bạn'},
'Linh':{'hien_thi':'Bạn Linh & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hoang':{'hien_thi':'Bạn Hoàng & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Thuy':{'hien_thi':'Bạn Thùy & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Giang__':{'hien_thi':'Bạn Giang & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Anh_Son':{'hien_thi':'Bạn Anh Sơn & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Chi_Nhu':{'hien_thi':'Chị Như & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Hang_Luan':{'hien_thi':'Bạn Hằng & người thương','loi_nhan':'','ten_xung':'vợ chồng em','ten_goi':'chị'},
'Toan_Que':{'hien_thi':'Bạn Toàn Quế & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Huyen_Cu':{'hien_thi':'Bạn Huyền Cù & người thương','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'bạn'},
'Vo_chong_Hang_kHai':{'hien_thi':'Gia đình bạn Hằng Khải','loi_nhan':'','ten_xung':'vợ chồng mình','ten_goi':'vợ chồng bạn'},
'Anh_Nhat':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_Hung':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Hien_Luong':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'vo_Bau':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_nhue':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Anh_Hau':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Quan_Phan':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
'Ba_Tan_Dat':{'hien_thi':'','loi_nhan':'','ten_xung':'','ten_goi':''},
};

$( document ).ready(function() {
    loadList();
});

var loadList = function(){
    var url = new URL(window.location);
    var c = url.searchParams.get("n");
    var my_default = list_data.default;
    var obj = list_data.default;
    if(c && list_data[c]){
        obj = list_data[c];
    }
    debugger
    if(obj.loi_nhan){
        $("#loi_nhan").text(obj.loi_nhan || my_default.loi_nhan);
    }
    
    $("#nguoi_dc_moi").text(obj.hien_thi || my_default.hien_thi);
    $("#ip_name").val(obj.hien_thi || my_default.hien_thi);
    $("#ip_phone").val(obj.sdt || my_default.sdt);
    $(".ten_xung").text(obj.ten_xung || my_default.ten_xung);
    $(".ten_goi").text(jsUcfirst(obj.ten_goi) || jsUcfirst(my_default.ten_goi));
    $("#show_bank").hide();
    if(obj.show_bank){
        $("#show_bank").show();
    }
    
}
function jsUcfirst(string) 
{
    if(string){
        return string.charAt(0).toUpperCase() + string.slice(1);
    }
    return string;
}
